### ISSUE TITLE
problem with shadows

### ISSUE THREAD

**Issue by kikiyoi** [Tech-How/Light-Theme-for-YouTube-Music#2]
![image](https://user-images.githubusercontent.com/78886819/169044129-b2e1a152-7a88-4bde-810d-8b4d7612f754.png)
can you then change the title to black？

**Comment by Tech-How** [comment]
Hi!
I've actually already replaced the logo. You can update to the latest version here, it should fix it.
https://github.com/Tech-How/Light-Theme-for-YouTube-Music/releases

Also, I see the shadow issue on the artwork. Can you let me know which browser you're using?
Also, if the logo isn't fixed, can you see if your computer can reach this page? https://i.ibb.co/DLjn7YZ/ytm-logo-beta.png

**Comment by kikiyoi** [comment]
thank you for your reply

> 你好！ 我实际上已经更换了标志。您可以在此处更新到最新版本，它应该可以修复它。 https://github.com/Tech-How/Light-Theme-for-YouTube-Music/releases
> 
> 另外，我看到艺术品上的阴影问题。你能告诉我你用的是什么浏览器吗？ 另外，如果logo不固定，你能看看你的电脑能不能访问这个页面吗？https://i.ibb.co/DLjn7YZ/ytm-logo-beta.png

Thank you for your reply
The version I am using is the latest version
I use google chrome（102.0.5005.49 beta ）
The logo link can be accessed normally

**Comment by kikiyoi** [comment]
> Hi! I've actually already replaced the logo. You can update to the latest version here, it should fix it. https://github.com/Tech-How/Light-Theme-for-YouTube-Music/releases
> 
> Also, I see the shadow issue on the artwork. Can you let me know which browser you're using? Also, if the logo isn't fixed, can you see if your computer can reach this page? https://i.ibb.co/DLjn7YZ/ytm-logo-beta.png

Thank you for your reply
The version I am using is the latest version
I use google chrome（102.0.5005.49 beta ）
The logo link can be accessed normally

**Comment by Tech-How** [comment]
Ok, thanks for the info. When you installed the theme, did you install it with the Stylish extension from [this page](https://userstyles.org/styles/207587/light-theme-for-youtube-music), or did you use a different style manager?

**Comment by kikiyoi** [comment]
> Ok, thanks for the info. When you installed the theme, did you install it with the Stylish extension from [this page](https://userstyles.org/styles/207587/light-theme-for-youtube-music), or did you use a different style manager?

Yes，But in home page，shadow normal
Problems only on the play pagee
![01](https://user-images.githubusercontent.com/78886819/169453438-0d72d348-3fab-4e9b-98d4-6b2ba07e5999.png)
![02](https://user-images.githubusercontent.com/78886819/169453450-f1a9dd74-7d0e-4716-a032-7817660b13f6.png)
![03](https://user-images.githubusercontent.com/78886819/169453467-67b832e6-db97-4dac-b1f0-06a1d38177d4.png)

**Comment by Tech-How** [comment]
Hmm... I see what's happening. It looks like something is pushing the borders or margins of the album artwork. I can't seem to replicate this, and I've never seen this happen before, but here are some things I would try:

- Make sure the page zoom is set to 100%
- Check if any other chrome extensions modify websites, like any YouTube extensions or themes
- Try on another computer or another browser

As for the logo, my first thought was that a different style extension was being used, since it does misbehave with other extensions. But it is the official extension, so I thought it could be a firewall or anti-virus, or network filtering? Although this wouldn't make much sense if the link can be accessed normally. The "ibb.co" link I sent earlier is where the theme points to for the logo. The theme works by hiding the actual logo and replacing it though, so it's crazy that my code that hides the logo doesn't work for some reason 🤔

If all else fails, you could remove the artwork shadow from the player page like this: https://drive.google.com/file/d/1ycFnvw0mSZBqqPXFfdCzt6fz_Yk0UVx4/view?usp=sharing

I'll definitely leave this open and update the thread if I'm able to re-create the issue sometime!

**Comment by kikiyoi** [comment]
> Hmm... I see what's happening. It looks like something is pushing the borders or margins of the album artwork. I can't seem to replicate this, and I've never seen this happen before, but here are some things I would try:
> 
> * Make sure the page zoom is set to 100%
> * Check if any other chrome extensions modify websites, like any YouTube extensions or themes
> * Try on another computer or another browser
> 
> As for the logo, my first thought was that a different style extension was being used, since it does misbehave with other extensions. But it is the official extension, so I thought it could be a firewall or anti-virus, or network filtering? Although this wouldn't make much sense if the link can be accessed normally. The "ibb.co" link I sent earlier is where the theme points to for the logo. The theme works by hiding the actual logo and replacing it though, so it's crazy that my code that hides the logo doesn't work for some reason 🤔
> 
> If all else fails, you could remove the artwork shadow from the player page like this: https://drive.google.com/file/d/1ycFnvw0mSZBqqPXFfdCzt6fz_Yk0UVx4/view?usp=sharing
> 
> I'll definitely leave this open and update the thread if I'm able to re-create the issue sometime!

Thank you very much！

**Comment by kikiyoi** [comment]
> Ok, thanks for the info. When you installed the theme, did you install it with the Stylish extension from [this page](https://userstyles.org/styles/207587/light-theme-for-youtube-music), or did you use a different style manager?

Hei.I have a new discovery
When i log out, problem disappears
But Just log in，problem reappears
In the end, logo question solved，I switched from Chinese to English in the settings, the problem is solved
https://drive.google.com/file/d/14G2d5fERG-fJBvHOP5LD-vB3IACt64lI/view
![1](https://user-images.githubusercontent.com/78886819/169649971-0c80ae78-b959-4c5f-8b35-64e206e8ecf6.png)

**Comment by Tech-How** [comment]
Wow, that's interesting. I actually tried switching my browser to Chinese earlier figuring it would be larger and push something out of the way, but it didn't work for me. Glad it's resolved!

**Comment by LucasN0611** [comment]
Hi, I'm having the same issue. When I'm logged out, the shadow looks fine, but once I log in the grey square around the album art is back. I've disabled all other extensions and tried another browser but it's still there.

**Comment by Tech-How** [comment]
Thanks for bringing this to my attention. I'll investigate this soon and try to find a solution. Do you mind telling me if you are on Windows or Mac, and which browser you're using? Also, do you have YouTube Music Premium?

**Comment by LucasN0611** [comment]
I'm on Windows, using the latest version of Chrome and I do have Premium

**Comment by Tech-How** [comment]
This appears to be a margin error with the audio/video switcher, which is only available to premium users. Could you try installing this beta theme to see if it resolves the issue while logged in? Just make sure to uninstall the current style first: https://userstyles.org/styles/256419/beta-style-82010475039

And could you also screenshot the result?

**Comment by LucasN0611** [comment]
That doesn't seem to work either, it just leaves the switcher dark

![image](https://user-images.githubusercontent.com/72567552/208308355-4215a89f-dc7e-45d4-9f62-c5f8c0fc0ba4.png)

**Comment by Tech-How** [comment]
I see. I've updated the beta style in that link, could you try updating it and seeing if that makes a difference? Also I apologize for the audio/video switcher, I don't have premium myself so I'm not able to style that element at the moment.

**Comment by LucasN0611** [comment]
That didn't work either. It completely removed the audio/video switcher though and defaults to playing video sometimes, it seems like randomly

**Comment by Tech-How** [comment]
I don't think it would default to playing video, that usually happens if you click the "top result", or if you click on a song from the official album page it will play the video. If you click the song under the songs tab via search it will play the song. I removed the audio video switcher for the time being because I don't have the necessary resources to style that element, but the new fix _should_ remove the gray border around the album artwork. Does it fix that on your end, or is the gray border still there?

**Comment by LucasN0611** [comment]
No, the grey border is still there

**Comment by Tech-How** [comment]
If you right-click on that border and select inspect, you should get a DevTools window to open. In the bottom you should see a styles pane similar to the one below. Could you send me a screenshot of that? It should have the element that is causing problems.
![image](https://user-images.githubusercontent.com/76794507/208309533-2b82acb5-efdb-4ede-a8e8-cdcffa61e8ef.png)

**Comment by LucasN0611** [comment]
![image](https://user-images.githubusercontent.com/72567552/208309722-dbb8ba2a-56c1-4676-aa76-fbefac9625ad.png)

**Comment by Tech-How** [comment]
That's odd, the second yt-img-shadow property is the one I forced to be transparent in hopes to fix it, but it appears it did not. I've updated the beta style to have it remove shadowing and rounded corners until I'm able to get a premium subscription and investigate this further. You can install that for now if you'd like, I hope to get this fixed eventually.

**Comment by LucasN0611** [comment]
I think I've fixed it. After messing about in the styles menu, I found that there are two backgrounds. I made the one you forced to be transparent red here, but there is still a bit of grey in the corners:
![image](https://user-images.githubusercontent.com/72567552/208310429-422d3193-6949-4d0e-bbb6-338d645bf009.png)

I went up a few elements and found the other background there. And when I made both of them transparent, it seemed to be working:
![image](https://user-images.githubusercontent.com/72567552/208310535-3ac6d161-1fc0-4038-be63-40774c9d575f.png)

**Comment by Tech-How** [comment]
I see! I actually noticed the second overriding "ytmusic-player" class earlier, but I can't get the CSS to dynamically change it, however I can get it to change by manually setting it in the DevTools window. I'll update this as soon as I can get it to be changed by means outside of inspect element.

**Comment by LucasN0611** [comment]
I think I figured it out; I just added this to the theme and is seems to be working fine now.
```
ytmusic-player {
    background-color: transparent;
}
```

**Comment by Tech-How** [comment]
Interesting, when I had tried that in Stylish it didn't carry over to the DevTools window, it was either crossed out or kept the default. I just updated this beta style again, do you mind confirming that this without any extra tweaks, works and solves the issue? Then I can get it pushed to the main update channel. Cheers! 🙌

https://userstyles.org/styles/256419/beta-style-82010475039

**Comment by LucasN0611** [comment]
Yeah, that works. Thanks for taking the time to update it!

**Comment by Tech-How** [comment]
Yeah and thanks for your cooperation! I'll release version 1.8 in the near future and include some other fixes hopefully.
